"""add_instagram_fields_to_company

Revision ID: 086771636110
Revises: c860e59d9eb2
Create Date: 2025-08-27 05:53:25.254148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086771636110'
down_revision = 'c860e59d9eb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('instagram_credentials', sa.JSON(), nullable=True))
    op.add_column('companies', sa.Column('instagram_account_id', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('instagram_username', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('instagram_page_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'instagram_page_id')
    op.drop_column('companies', 'instagram_username')
    op.drop_column('companies', 'instagram_account_id')
    op.drop_column('companies', 'instagram_credentials')
    # ### end Alembic commands ###
