"""add_replied_column_to_chat

Revision ID: 39dccaae8947
Revises: 21bec2794764
Create Date: 2025-07-28 07:47:05.109821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39dccaae8947'
down_revision = '21bec2794764'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('replied', sa.BOOLEAN(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'replied')
    # ### end Alembic commands ###
