"""add_action_required_to_chat

Revision ID: 417ea5f4882a
Revises: 95dd4b9848de
Create Date: 2025-07-29 14:37:26.124583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417ea5f4882a'
down_revision = '95dd4b9848de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('action_required', sa.Boolean(), nullable=True))
    op.add_column('chat', sa.Column('action_reason', sa.String(), nullable=True))
    op.add_column('chat', sa.Column('action_type', sa.String(), nullable=True))
    op.add_column('chat', sa.Column('urgency', sa.String(), nullable=True))
    
    # Handle existing null values before making columns NOT NULL
    op.execute("UPDATE chat SET message_id = 'legacy-' || id::text WHERE message_id IS NULL")
    op.execute("UPDATE chat SET thread_id = 'legacy-thread-' || id::text WHERE thread_id IS NULL")
    op.execute("UPDATE chat SET from_email = 'unknown@example.com' WHERE from_email IS NULL")
    op.execute("UPDATE chat SET to_email = 'unknown@example.com' WHERE to_email IS NULL")
    op.execute("UPDATE chat SET subject = '(No Subject)' WHERE subject IS NULL")
    
    op.alter_column('chat', 'thread_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat', 'message_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat', 'from_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat', 'to_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_chat_from_email', table_name='chat')
    op.drop_index('ix_chat_message_id', table_name='chat')
    op.create_index(op.f('ix_chat_message_id'), 'chat', ['message_id'], unique=False)
    op.drop_constraint('chat_company_id_fkey', 'chat', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('chat_company_id_fkey', 'chat', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_chat_message_id'), table_name='chat')
    op.create_index('ix_chat_message_id', 'chat', ['message_id'], unique=True)
    op.create_index('ix_chat_from_email', 'chat', ['from_email'], unique=False)
    op.alter_column('chat', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chat', 'to_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chat', 'from_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chat', 'message_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chat', 'thread_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('chat', 'action_required')
    op.drop_column('chat', 'action_reason')
    op.drop_column('chat', 'action_type')
    op.drop_column('chat', 'urgency')
    # ### end Alembic commands ###
