"""rename flow_context to flow_builder_data and add new flow_context column

Revision ID: 5afd5ac58a4e
Revises: f570a0e0f575
Create Date: 2025-08-12 05:42:57.958614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5afd5ac58a4e'
down_revision = 'f570a0e0f575'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename flow_context to flow_builder_data
    op.alter_column('company_context', 'flow_context', new_column_name='flow_builder_data')
    
    # Add new flow_context column for AI-generated text
    op.add_column('company_context', sa.Column('flow_context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the new flow_context column
    op.drop_column('company_context', 'flow_context')
    
    # Rename flow_builder_data back to flow_context
    op.alter_column('company_context', 'flow_builder_data', new_column_name='flow_context')
    # ### end Alembic commands ###
