"""Add foreign key constraint to channel_context

Revision ID: 74d59b797615
Revises: ce8a5778367a
Create Date: 2025-08-07 10:29:15.737888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d59b797615'
down_revision = 'ce8a5778367a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'channel_context', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channel_context', type_='foreignkey')
    # ### end Alembic commands ###
