"""Add Outlook fields to Company model

Revision ID: 7549ab6af7a7
Revises: 8cc813a6ba28
Create Date: 2025-08-04 12:42:59.520403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7549ab6af7a7'
down_revision = '8cc813a6ba28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('outlook_box_credentials', sa.JSON(), nullable=True))
    op.add_column('companies', sa.Column('outlook_box_email', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('outlook_box_username', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'outlook_box_username')
    op.drop_column('companies', 'outlook_box_email')
    op.drop_column('companies', 'outlook_box_credentials')
    # ### end Alembic commands ###
