"""add_feedback_to_chat

Revision ID: 8cc813a6ba28
Revises: 417ea5f4882a
Create Date: 2025-07-30 09:39:05.101732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc813a6ba28'
down_revision = '417ea5f4882a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('feedback', sa.String(), nullable=True))
    op.alter_column('chat', 'thread_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chat', 'message_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chat', 'from_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chat', 'to_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chat', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_chat_message_id', table_name='chat')
    op.create_index(op.f('ix_chat_message_id'), 'chat', ['message_id'], unique=True)
    op.create_index(op.f('ix_chat_from_email'), 'chat', ['from_email'], unique=False)
    op.create_foreign_key(None, 'chat', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.drop_index(op.f('ix_chat_from_email'), table_name='chat')
    op.drop_index(op.f('ix_chat_message_id'), table_name='chat')
    op.create_index('ix_chat_message_id', 'chat', ['message_id'], unique=False)
    op.alter_column('chat', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat', 'to_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat', 'from_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat', 'message_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat', 'thread_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('chat', 'feedback')
    # ### end Alembic commands ###
