"""add_channel_auto_reply_settings_table

Revision ID: 95dd4b9848de
Revises: 8c4c379fa71c
Create Date: 2025-07-29 03:09:59.745344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95dd4b9848de'
down_revision = '8c4c379fa71c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_auto_reply_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('enable_auto_reply', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_auto_reply_settings_channel_id'), 'channel_auto_reply_settings', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_auto_reply_settings_id'), 'channel_auto_reply_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_auto_reply_settings_id'), table_name='channel_auto_reply_settings')
    op.drop_index(op.f('ix_channel_auto_reply_settings_channel_id'), table_name='channel_auto_reply_settings')
    op.drop_table('channel_auto_reply_settings')
    # ### end Alembic commands ###
