"""add_logo_url_to_companies

Revision ID: ab1cc784cace
Revises: 5afd5ac58a4e
Create Date: 2025-08-12 15:22:41.148074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1cc784cace'
down_revision = '5afd5ac58a4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'logo_url')
    # ### end Alembic commands ###
