"""add_notification_read_to_chat

Revision ID: c860e59d9eb2
Revises: ab1cc784cace
Create Date: 2025-08-15 08:40:12.043141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c860e59d9eb2'
down_revision = 'ab1cc784cace'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('notification_read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'notification_read')
    # ### end Alembic commands ###
