"""Add channel_context table properly

Revision ID: ce8a5778367a
Revises: 7549ab6af7a7
Create Date: 2025-08-07 10:14:36.831313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8a5778367a'
down_revision = '7549ab6af7a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('channel_context', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_context_channel_id'), 'channel_context', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_context_company_id'), 'channel_context', ['company_id'], unique=False)
    op.create_index(op.f('ix_channel_context_id'), 'channel_context', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_context_id'), table_name='channel_context')
    op.drop_index(op.f('ix_channel_context_company_id'), table_name='channel_context')
    op.drop_index(op.f('ix_channel_context_channel_id'), table_name='channel_context')
    op.drop_table('channel_context')
    # ### end Alembic commands ###
