"""add_facebook_fields_to_company

Revision ID: e461cd76bdfc
Revises: 086771636110
Create Date: 2025-08-27 11:01:32.354088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e461cd76bdfc'
down_revision = '086771636110'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('facebook_box_credentials', sa.JSON(), nullable=True))
    op.add_column('companies', sa.Column('facebook_box_page_id', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('facebook_box_page_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'facebook_box_page_name')
    op.drop_column('companies', 'facebook_box_page_id')
    op.drop_column('companies', 'facebook_box_credentials')
    # ### end Alembic commands ###
