"""Add company_context table

Revision ID: f570a0e0f575
Revises: fba6e0aeb404
Create Date: 2025-08-12 04:22:17.047708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f570a0e0f575'
down_revision = 'fba6e0aeb404'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('text_context', sa.Text(), nullable=True),
    sa.Column('flow_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_context_id'), 'company_context', ['id'], unique=False)
    op.drop_index('ix_chat_thread_id', table_name='chat')
    op.create_index(op.f('ix_chat_channel_id'), 'chat', ['channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_channel_id'), table_name='chat')
    op.create_index('ix_chat_thread_id', 'chat', ['channel_id'], unique=False)
    op.drop_index(op.f('ix_company_context_id'), table_name='company_context')
    op.drop_table('company_context')
    # ### end Alembic commands ###
